package commands

import (
	"github.com/gettako/tako/internal/console/cli"
)

type HelloCommand struct{}

func (c *HelloCommand) Name() string { return "hello" }

func (c *HelloCommand) Description() string { return "Prints a greeting to the terminal" }

func (c *HelloCommand) Execute(ctx *cli.Context, args []string) error {
	name := ctx.OptionString("name")
	if name == "" {
		name = "World"
	}
	ctx.Info("Hello, " + name + "!\nThis output was generated by the Tako CLI Kernel, bypassing the TUI entirely.")
	return nil
}
